dev branch

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -25,7 +25,7 @@ steps:
         fi
 
   # Step 3: Sync DAGs to the appropriate Composer bucket
-  - id: "Upload"
+    - id: "Upload"
     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args:
@@ -33,26 +33,28 @@ steps:
       - |
         echo $_BRANCH_NAME
         echo "Deploying DAGs to the Composer bucket for branch: $_BRANCH_NAME"
-        case "$_BRANCH_NAME" in 
-          "dev")
-            TARGET_BUCKET="gs://asia-southeast2-dev-env-4cd8345a-bucket/dags"
-            ;;
-          "sit")
-            TARGET_BUCKET="gs://asia-southeast2-sit-env-f9237651-bucket/dags"
-            ;;
-          "uat")
-            TARGET_BUCKET="gs://asia-southeast2-uat-env-bucket/dags"
-            ;;
-          "production")
-            TARGET_BUCKET="gs://asia-southeast2-prod-env-bucket/dags"
-            ;;
-          *)
-            echo "Error: Unsupported branch $_BRANCH_NAME"
-            exit 1
-            ;;
-        esac
-        echo "Syncing DAGs to $TARGET_BUCKET..."
-        gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags "$TARGET_BUCKET" 
+        if [ "$_BRANCH_NAME" = "dev" ]; then
+          gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags gs://asia-southeast2-dev-env-4cd8345a-bucket/dags
+        elif [ "$_BRANCH_NAME" = "sit" ]; then
+          gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags gs://asia-southeast2-sit-env-f9237651-bucket/dags
+        elif [ "$_BRANCH_NAME" = "uat" ]; then
+          gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags gs://asia-southeast2-uat-env-bucket/dags
+        elif [ "$_BRANCH_NAME" = "production" ]; then
+          gsutil -m rsync -r -d /workspace/dap-composer-cicd/dags gs://asia-southeast2-prod-env-bucket/dags
+        else
+          echo "Error: Unsupported branch $_BRANCH_NAME"
+          exit 1
+        fi
+
+
+  - id: "Debug"
+    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
+    entrypoint: bash
+    args:
+      - -c
+      - |
+        echo "Environment variables:"
+        env
 
 options:
   logging: CLOUD_LOGGING_ONLY
